---
name: SpyOne
main: TimmYCode\SpyOne
version: 1.0.0
api: 5.0.0
author: TimmYCode

permissions:
  spyone.ignore:
    description: "Ignores players with specified permission"
    default: false
  spyone.notify:
    description: "Get a notification if player is accused of cheating"
    default: false
...
